// <auto-generated />
using System;
using Ex3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ex3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Ex3.Models.Agent", b =>
                {
                    b.Property<int>("AgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentName")
                        .HasColumnType("TEXT");

                    b.HasKey("AgentID");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentID = 1,
                            Address = "Address1",
                            AgentName = "Agent1"
                        },
                        new
                        {
                            AgentID = 2,
                            Address = "Address2",
                            AgentName = "Agent2"
                        },
                        new
                        {
                            AgentID = 3,
                            Address = "Address3",
                            AgentName = "Agent3"
                        },
                        new
                        {
                            AgentID = 4,
                            Address = "Address4",
                            AgentName = "Agent4"
                        },
                        new
                        {
                            AgentID = 5,
                            Address = "Address5",
                            AgentName = "Agent5"
                        },
                        new
                        {
                            AgentID = 6,
                            Address = "Address6",
                            AgentName = "Agent6"
                        },
                        new
                        {
                            AgentID = 7,
                            Address = "Address7",
                            AgentName = "Agent7"
                        },
                        new
                        {
                            AgentID = 8,
                            Address = "Address8",
                            AgentName = "Agent8"
                        },
                        new
                        {
                            AgentID = 9,
                            Address = "Address9",
                            AgentName = "Agent9"
                        },
                        new
                        {
                            AgentID = 10,
                            Address = "Address10",
                            AgentName = "Agent10"
                        },
                        new
                        {
                            AgentID = 11,
                            Address = "Address11",
                            AgentName = "Agent11"
                        },
                        new
                        {
                            AgentID = 12,
                            Address = "Address12",
                            AgentName = "Agent12"
                        },
                        new
                        {
                            AgentID = 13,
                            Address = "Address13",
                            AgentName = "Agent13"
                        },
                        new
                        {
                            AgentID = 14,
                            Address = "Address14",
                            AgentName = "Agent14"
                        },
                        new
                        {
                            AgentID = 15,
                            Address = "Address15",
                            AgentName = "Agent15"
                        });
                });

            modelBuilder.Entity("Ex3.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            ItemName = "Item1",
                            Size = "Size1"
                        },
                        new
                        {
                            ItemID = 2,
                            ItemName = "Item2",
                            Size = "Size2"
                        },
                        new
                        {
                            ItemID = 3,
                            ItemName = "Item3",
                            Size = "Size3"
                        },
                        new
                        {
                            ItemID = 4,
                            ItemName = "Item4",
                            Size = "Size4"
                        },
                        new
                        {
                            ItemID = 5,
                            ItemName = "Item5",
                            Size = "Size5"
                        },
                        new
                        {
                            ItemID = 6,
                            ItemName = "Item6",
                            Size = "Size6"
                        },
                        new
                        {
                            ItemID = 7,
                            ItemName = "Item7",
                            Size = "Size7"
                        },
                        new
                        {
                            ItemID = 8,
                            ItemName = "Item8",
                            Size = "Size8"
                        },
                        new
                        {
                            ItemID = 9,
                            ItemName = "Item9",
                            Size = "Size9"
                        },
                        new
                        {
                            ItemID = 10,
                            ItemName = "Item10",
                            Size = "Size10"
                        },
                        new
                        {
                            ItemID = 11,
                            ItemName = "Item11",
                            Size = "Size11"
                        },
                        new
                        {
                            ItemID = 12,
                            ItemName = "Item12",
                            Size = "Size12"
                        },
                        new
                        {
                            ItemID = 13,
                            ItemName = "Item13",
                            Size = "Size13"
                        },
                        new
                        {
                            ItemID = 14,
                            ItemName = "Item14",
                            Size = "Size14"
                        },
                        new
                        {
                            ItemID = 15,
                            ItemName = "Item15",
                            Size = "Size15"
                        });
                });

            modelBuilder.Entity("Ex3.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgentID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.HasIndex("AgentID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            AgentID = 1,
                            OrderDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 2,
                            AgentID = 2,
                            OrderDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 3,
                            AgentID = 3,
                            OrderDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 4,
                            AgentID = 4,
                            OrderDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 5,
                            AgentID = 5,
                            OrderDate = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 6,
                            AgentID = 6,
                            OrderDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 7,
                            AgentID = 7,
                            OrderDate = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 8,
                            AgentID = 8,
                            OrderDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 9,
                            AgentID = 9,
                            OrderDate = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 10,
                            AgentID = 10,
                            OrderDate = new DateTime(2025, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 11,
                            AgentID = 11,
                            OrderDate = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 12,
                            AgentID = 12,
                            OrderDate = new DateTime(2025, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 13,
                            AgentID = 13,
                            OrderDate = new DateTime(2025, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 14,
                            AgentID = 14,
                            OrderDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 15,
                            AgentID = 15,
                            OrderDate = new DateTime(2025, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ex3.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 1,
                            UnitAmount = 10.0m
                        },
                        new
                        {
                            ID = 2,
                            ItemID = 2,
                            OrderID = 2,
                            Quantity = 2,
                            UnitAmount = 20.0m
                        },
                        new
                        {
                            ID = 3,
                            ItemID = 3,
                            OrderID = 3,
                            Quantity = 3,
                            UnitAmount = 30.0m
                        },
                        new
                        {
                            ID = 4,
                            ItemID = 4,
                            OrderID = 4,
                            Quantity = 4,
                            UnitAmount = 40.0m
                        },
                        new
                        {
                            ID = 5,
                            ItemID = 5,
                            OrderID = 5,
                            Quantity = 5,
                            UnitAmount = 50.0m
                        },
                        new
                        {
                            ID = 6,
                            ItemID = 6,
                            OrderID = 6,
                            Quantity = 6,
                            UnitAmount = 60.0m
                        },
                        new
                        {
                            ID = 7,
                            ItemID = 7,
                            OrderID = 7,
                            Quantity = 7,
                            UnitAmount = 70.0m
                        },
                        new
                        {
                            ID = 8,
                            ItemID = 8,
                            OrderID = 8,
                            Quantity = 8,
                            UnitAmount = 80.0m
                        },
                        new
                        {
                            ID = 9,
                            ItemID = 9,
                            OrderID = 9,
                            Quantity = 9,
                            UnitAmount = 90.0m
                        },
                        new
                        {
                            ID = 10,
                            ItemID = 10,
                            OrderID = 10,
                            Quantity = 10,
                            UnitAmount = 100.0m
                        },
                        new
                        {
                            ID = 11,
                            ItemID = 11,
                            OrderID = 11,
                            Quantity = 11,
                            UnitAmount = 110.0m
                        },
                        new
                        {
                            ID = 12,
                            ItemID = 12,
                            OrderID = 12,
                            Quantity = 12,
                            UnitAmount = 120.0m
                        },
                        new
                        {
                            ID = 13,
                            ItemID = 13,
                            OrderID = 13,
                            Quantity = 13,
                            UnitAmount = 130.0m
                        },
                        new
                        {
                            ID = 14,
                            ItemID = 14,
                            OrderID = 14,
                            Quantity = 14,
                            UnitAmount = 140.0m
                        },
                        new
                        {
                            ID = 15,
                            ItemID = 15,
                            OrderID = 15,
                            Quantity = 15,
                            UnitAmount = 150.0m
                        });
                });

            modelBuilder.Entity("Ex3.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Lock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "user1@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User1"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "user2@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User2"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "user3@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User3"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "user4@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User4"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "user5@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User5"
                        },
                        new
                        {
                            UserID = 6,
                            Email = "user6@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User6"
                        },
                        new
                        {
                            UserID = 7,
                            Email = "user7@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User7"
                        },
                        new
                        {
                            UserID = 8,
                            Email = "user8@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User8"
                        },
                        new
                        {
                            UserID = 9,
                            Email = "user9@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User9"
                        },
                        new
                        {
                            UserID = 10,
                            Email = "user10@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User10"
                        },
                        new
                        {
                            UserID = 11,
                            Email = "user11@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User11"
                        },
                        new
                        {
                            UserID = 12,
                            Email = "user12@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User12"
                        },
                        new
                        {
                            UserID = 13,
                            Email = "user13@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User13"
                        },
                        new
                        {
                            UserID = 14,
                            Email = "user14@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User14"
                        },
                        new
                        {
                            UserID = 15,
                            Email = "user15@example.com",
                            Lock = false,
                            Password = "password",
                            UserName = "User15"
                        });
                });

            modelBuilder.Entity("Ex3.Models.Order", b =>
                {
                    b.HasOne("Ex3.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Ex3.Models.OrderDetail", b =>
                {
                    b.HasOne("Ex3.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ex3.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ex3.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
